### ISSUE TITLE
feature query

### ISSUE THREAD

**Issue by jun0wanan** [crodriguezo/DORi#2]
hi,

          Object Features  is i3d feature or resnet feature ?

**Comment by crodriguezo** [comment]
Hi @jun0wanan,

Object features are ResNET features extracted using visual genome/Faster RCNN. We extracted spatial features for the sharpest frame in the clip used to get an activity representation (i3d). Please take a look at section 3.1.2 human and object node in our paper.

**Comment by jun0wanan** [comment]
> Hi @jun0wanan,
> 
> Object features are ResNET features extracted using visual genome/Faster RCNN. We extracted spatial features for the sharpest frame in the clip used to get an activity representation (i3d). Please take a look at section 3.1.2 human and object node in our paper.

Thank you ! I am sorry to disturb you again ..  What i3d code repo you use ? Can you give a link~? :-)

best,
wishes

**Comment by crodriguezo** [comment]
For extracting video features (i3d) I used  https://github.com/piergiaj/pytorch-i3d and object features https://github.com/peteanderson80/bottom-up-attention

**Comment by jun0wanan** [comment]
> For extracting video features (i3d) I used https://github.com/piergiaj/pytorch-i3d and object features https://github.com/peteanderson80/bottom-up-attention

About i3d:

What stride  did  you use?  What thing did you do ,if you have not enough gpu?( maybe the same as  https://github.com/piergiaj/pytorch-i3d? or you have change the setting )  ╥﹏╥... Thank you!

Best,
wishes

**Comment by jun0wanan** [comment]
> For extracting video features (i3d) I used https://github.com/piergiaj/pytorch-i3d and object features https://github.com/peteanderson80/bottom-up-attention

I am so sorry to disturb you . I want to get i3d by myself ,however I find the gpu is not enough ..
