### ISSUE TITLE
YouCookII: p_start > p_end

### ISSUE THREAD

**Issue by TracyYXChen** [crodriguezo/DORi#4]
Thanks for releasing the code! While reproducing the YouCookII experiment, I noticed several predictions have p_start > p_end, e.g., `"0": {"p_start": 165.504, "p_end": 111.7819}, "15": {"p_start": 264.6263, "p_end": 58.7317}`. Do you have any ideas why? Thanks!

**Comment by crodriguezo** [comment]
We also see that issue happening in some predictions.  We propose a solution for it here https://arxiv.org/pdf/2112.10066.pdf please take a look at eq.4

**Comment by TracyYXChen** [comment]
Thanks! I wonder whether it's possible to fix the issue in DORi with minimal revisions. If so, in file `utils/visualization.py`  line 50-51, after `startings = np.argmax(pred_start)`, should we get the index (suppose it's `a`), and force the `endings= np.argmax(pred_end[a+1: ])`; or should we try to find a pair `[a, b]` that maximize `pred_start[a] + pred_end[b]`?

**Comment by TracyYXChen** [comment]
And I'm also interested in reading the supplementary materials of DORi. Could you please send a copy to me? ([ychen151@umd.edu](ychen151@umd.edu)), thanks!

**Comment by crodriguezo** [comment]
check this for the supp https://arxiv.org/pdf/2010.06260.pdf

**Comment by crodriguezo** [comment]
> Thanks! I wonder whether it's possible to fix the issue in DORi with minimal revisions. If so, in file `utils/visualization.py` line 50-51, after `startings = np.argmax(pred_start)`, should we get the index (suppose it's `a`), and force the `endings= np.argmax(pred_end[a+1: ])`; or should we try to find a pair `[a, b]` that maximize `pred_start[a] + pred_end[b]`?

It is possible, but we weren't interested in doing too many things in the postprocessing stage. We might be wrong about it

**Comment by TracyYXChen** [comment]
Thanks for your prompt reply! I agree that adding constraints to the postprocessing stage sounds hacky. Could you please recommend any code revisions to address this issue?
